#we can directly run rabbitmq image as we dont have anything to configure
#docker run -d --network roboshop --name rabbitmq -e RABBITMQ_DEFAULT_USER=roboshop -e RABBITMQ_DEFAULT_PASS=roboshop123 rabbitmq:3
